version: 1
accounts:
- name: validator
  coins:
  - 1000000000000nuahp
- name: test
  coins:
  - 10000nuah
  - 10000aga
  - 1000000000000nuahp
- name: alice
  coins:
  - 20000token
  - 200000000stake
- name: bob
  coins:
  - 10000token
  - 100000000stake
faucet:
  name: bob
  coins:
  - 5token
  - 100000nuahp
client:
  typescript:
    path: ts-client
  openapi:
    path: docs/static/openapi.yml
genesis:
  app_state:
    staking:
      params:
        bond_denom: nuahp
validators:
- name: validator
  bonded: 1000000000000nuahp
