// Generated by Ignite ignite.com/cli

import { StdFee } from "@cosmjs/launchpad";
import { SigningStargateClient, DeliverTxResponse } from "@cosmjs/stargate";
import { EncodeObject, GeneratedType, OfflineSigner, Registry } from "@cosmjs/proto-signing";
import { msgTypes } from './registry';
import { IgniteClient } from "../client"
import { MissingWalletError } from "../helpers"
import { Api } from "./rest";
import { MsgCancelBuyOrder } from "./types/nuah/exchange/tx";
import { MsgSendBuyOrder } from "./types/nuah/exchange/tx";
import { MsgSendSellOrder } from "./types/nuah/exchange/tx";
import { MsgCancelSellOrder } from "./types/nuah/exchange/tx";
import { MsgSendCreatePair } from "./types/nuah/exchange/tx";

import { BuyOrderBook as typeBuyOrderBook} from "./types"
import { DenomTrace as typeDenomTrace} from "./types"
import { ExchangePacketData as typeExchangePacketData} from "./types"
import { NoData as typeNoData} from "./types"
import { CreatePairPacketData as typeCreatePairPacketData} from "./types"
import { CreatePairPacketAck as typeCreatePairPacketAck} from "./types"
import { SellOrderPacketData as typeSellOrderPacketData} from "./types"
import { SellOrderPacketAck as typeSellOrderPacketAck} from "./types"
import { BuyOrderPacketData as typeBuyOrderPacketData} from "./types"
import { BuyOrderPacketAck as typeBuyOrderPacketAck} from "./types"
import { Params as typeParams} from "./types"
import { SellOrderBook as typeSellOrderBook} from "./types"

export { MsgCancelBuyOrder, MsgSendBuyOrder, MsgSendSellOrder, MsgCancelSellOrder, MsgSendCreatePair };

type sendMsgCancelBuyOrderParams = {
  value: MsgCancelBuyOrder,
  fee?: StdFee,
  memo?: string
};

type sendMsgSendBuyOrderParams = {
  value: MsgSendBuyOrder,
  fee?: StdFee,
  memo?: string
};

type sendMsgSendSellOrderParams = {
  value: MsgSendSellOrder,
  fee?: StdFee,
  memo?: string
};

type sendMsgCancelSellOrderParams = {
  value: MsgCancelSellOrder,
  fee?: StdFee,
  memo?: string
};

type sendMsgSendCreatePairParams = {
  value: MsgSendCreatePair,
  fee?: StdFee,
  memo?: string
};


type msgCancelBuyOrderParams = {
  value: MsgCancelBuyOrder,
};

type msgSendBuyOrderParams = {
  value: MsgSendBuyOrder,
};

type msgSendSellOrderParams = {
  value: MsgSendSellOrder,
};

type msgCancelSellOrderParams = {
  value: MsgCancelSellOrder,
};

type msgSendCreatePairParams = {
  value: MsgSendCreatePair,
};


export const registry = new Registry(msgTypes);

type Field = {
	name: string;
	type: unknown;
}
function getStructure(template) {
	const structure: {fields: Field[]} = { fields: [] }
	for (let [key, value] of Object.entries(template)) {
		let field = { name: key, type: typeof value }
		structure.fields.push(field)
	}
	return structure
}
const defaultFee = {
  amount: [],
  gas: "200000",
};

interface TxClientOptions {
  addr: string
	prefix: string
	signer?: OfflineSigner
}

export const txClient = ({ signer, prefix, addr }: TxClientOptions = { addr: "http://localhost:26657", prefix: "cosmos" }) => {

  return {
		
		async sendMsgCancelBuyOrder({ value, fee, memo }: sendMsgCancelBuyOrderParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgCancelBuyOrder: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgCancelBuyOrder({ value: MsgCancelBuyOrder.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgCancelBuyOrder: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgSendBuyOrder({ value, fee, memo }: sendMsgSendBuyOrderParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgSendBuyOrder: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgSendBuyOrder({ value: MsgSendBuyOrder.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgSendBuyOrder: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgSendSellOrder({ value, fee, memo }: sendMsgSendSellOrderParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgSendSellOrder: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgSendSellOrder({ value: MsgSendSellOrder.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgSendSellOrder: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgCancelSellOrder({ value, fee, memo }: sendMsgCancelSellOrderParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgCancelSellOrder: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgCancelSellOrder({ value: MsgCancelSellOrder.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgCancelSellOrder: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgSendCreatePair({ value, fee, memo }: sendMsgSendCreatePairParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgSendCreatePair: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgSendCreatePair({ value: MsgSendCreatePair.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgSendCreatePair: Could not broadcast Tx: '+ e.message)
			}
		},
		
		
		msgCancelBuyOrder({ value }: msgCancelBuyOrderParams): EncodeObject {
			try {
				return { typeUrl: "/nuah.exchange.MsgCancelBuyOrder", value: MsgCancelBuyOrder.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgCancelBuyOrder: Could not create message: ' + e.message)
			}
		},
		
		msgSendBuyOrder({ value }: msgSendBuyOrderParams): EncodeObject {
			try {
				return { typeUrl: "/nuah.exchange.MsgSendBuyOrder", value: MsgSendBuyOrder.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgSendBuyOrder: Could not create message: ' + e.message)
			}
		},
		
		msgSendSellOrder({ value }: msgSendSellOrderParams): EncodeObject {
			try {
				return { typeUrl: "/nuah.exchange.MsgSendSellOrder", value: MsgSendSellOrder.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgSendSellOrder: Could not create message: ' + e.message)
			}
		},
		
		msgCancelSellOrder({ value }: msgCancelSellOrderParams): EncodeObject {
			try {
				return { typeUrl: "/nuah.exchange.MsgCancelSellOrder", value: MsgCancelSellOrder.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgCancelSellOrder: Could not create message: ' + e.message)
			}
		},
		
		msgSendCreatePair({ value }: msgSendCreatePairParams): EncodeObject {
			try {
				return { typeUrl: "/nuah.exchange.MsgSendCreatePair", value: MsgSendCreatePair.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgSendCreatePair: Could not create message: ' + e.message)
			}
		},
		
	}
};

interface QueryClientOptions {
  addr: string
}

export const queryClient = ({ addr: addr }: QueryClientOptions = { addr: "http://localhost:1317" }) => {
  return new Api({ baseURL: addr });
};

class SDKModule {
	public query: ReturnType<typeof queryClient>;
	public tx: ReturnType<typeof txClient>;
	public structure: Record<string,unknown>;
	public registry: Array<[string, GeneratedType]> = [];

	constructor(client: IgniteClient) {		
	
		this.query = queryClient({ addr: client.env.apiURL });		
		this.updateTX(client);
		this.structure =  {
						BuyOrderBook: getStructure(typeBuyOrderBook.fromPartial({})),
						DenomTrace: getStructure(typeDenomTrace.fromPartial({})),
						ExchangePacketData: getStructure(typeExchangePacketData.fromPartial({})),
						NoData: getStructure(typeNoData.fromPartial({})),
						CreatePairPacketData: getStructure(typeCreatePairPacketData.fromPartial({})),
						CreatePairPacketAck: getStructure(typeCreatePairPacketAck.fromPartial({})),
						SellOrderPacketData: getStructure(typeSellOrderPacketData.fromPartial({})),
						SellOrderPacketAck: getStructure(typeSellOrderPacketAck.fromPartial({})),
						BuyOrderPacketData: getStructure(typeBuyOrderPacketData.fromPartial({})),
						BuyOrderPacketAck: getStructure(typeBuyOrderPacketAck.fromPartial({})),
						Params: getStructure(typeParams.fromPartial({})),
						SellOrderBook: getStructure(typeSellOrderBook.fromPartial({})),
						
		};
		client.on('signer-changed',(signer) => {			
		 this.updateTX(client);
		})
	}
	updateTX(client: IgniteClient) {
    const methods = txClient({
        signer: client.signer,
        addr: client.env.rpcURL,
        prefix: client.env.prefix ?? "cosmos",
    })
	
    this.tx = methods;
    for (let m in methods) {
        this.tx[m] = methods[m].bind(this.tx);
    }
	}
};

const Module = (test: IgniteClient) => {
	return {
		module: {
			NuahExchange: new SDKModule(test)
		},
		registry: msgTypes
  }
}
export default Module;